### ISSUE TITLE
id값이 null로 나옵니다

### ISSUE THREAD

**Issue by ddamddi** [CAU-OSS-2019/team-project-team13#14]
develop 브랜치에 있는게 젤 최신이신거같은데 현재, extension안에 dom 구조를 클릭하면 id값이 null 값이 나오는 버그가 발견되었습니다.

**Comment by ddamddi** [comment]
![image](https://user-images.githubusercontent.com/37342126/59909018-b31c2380-9449-11e9-88cc-a15c59d74f99.png)

Dom Struct Print 이후에 dom 구조를 클릭한다음
 다시 확장프로그램을 켜서 Dom Struct Print를 누르면 다음과 같이 랜덤하게 노란색으로 칠해지네요

**Comment by choiyooung** [comment]
연속적으로 파란색 블럭을 마우스로 이동할 경우 발생하는 문제입니다. 하지만 아직 좋은 아이더가 떠오르지 않아 해당 문제를 전부 해결하지 못하고 있습니다. 더 좋은 방법이 있으시면, 의견 제시해주시면 감사하겠습니다.
