### ISSUE TITLE
Dom struct Print 버튼을 2번 이상 클릭하면 잘못된 동작을 함

### ISSUE THREAD

**Issue by njw1204** [CAU-OSS-2019/team-project-team13#5]
**Dom struct Print** 버튼을 2번 이상 클릭하면 아래의 사진과 같이 이상한 요소가 계속해서 추가됩니다. 현재 페이지 URL과 관계없이 발생하는 오류입니다.

![image](https://user-images.githubusercontent.com/38099251/58433640-1c32a480-80f3-11e9-9596-7a8ea30a58c1.png)

<br />

아래의 사진처럼 나오면 안 될 메시지박스도 출력됩니다. 처음 클릭했을때는 메시지박스가 1개, 두번째에는 메시지박스가 2개, 세번째에는 3개 나오는 이상한 현상도 발생합니다.

![image](https://user-images.githubusercontent.com/38099251/58433693-4c7a4300-80f3-11e9-9216-a49066f1eb44.png)

**Comment by njw1204** [comment]
기대하는 동작은 현재 html 구조에 맞춰서 (동적으로 변경되었을 수도 있으니) 다시 로드해 출력하는 것입니다.

**Comment by njw1204** [comment]
#7

**Comment by choiyooung** [comment]
현재 확인 했습니다. 이 부분 검토하겠습니다.
